//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oswos.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Website
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string HostName { get; set; }
        public string Path { get; set; }
    }
}
